### ISSUE TITLE
Support Jenkins CI

### ISSUE THREAD

**Issue by serra** [GitTools/GitVersion#313]
See the comment thread in #288.

I'll see if I can get something to work in my environment. I'll open a PR then.

* Implement Jenkins.cs (compare: [TeamCity.js][tc]), with tests. Check for existence of `JENKINS_URL` to confirm that we're running from within the context of a job in Jenkins. See [wiki/Command-Line-Tool#directly-on-build-server](https://github.com/ParticularLabs/GitVersion/wiki/Command-Line-Tool#directly-on-build-server)
* choose parameter name to set [see variables in wiki](https://github.com/ParticularLabs/GitVersion/wiki/Variables)
* find out how to set parameter values from within a job

Current implementations write a message to the build output. This message should then be picked up by the build server. In Team City, this concept is called [Service Messages][svcmsg].

AFAIK a similar concept is *not* available in Jenkins CI, which would mean the Jenkins implementation would be conceptually different. Before picking this up, I'll wait for some answers to my [post to the Jenkins newsgroup](https://groups.google.com/forum/#!topic/jenkinsci-users/b7n1iAjJ7pA).

 [svcmsg]: http://confluence.jetbrains.com/display/TCD65/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-AddingorChangingaBuildParameterfromaBuildStep
 [tc]: https://github.com/ParticularLabs/GitVersion/blob/master/GitVersionCore/BuildServers/TeamCity.cs
 [oldquestion]: https://groups.google.com/forum/#!searchin/jenkinsci-users/service$20messages/jenkinsci-users/7ktpX1RDpiY/Sy8jmf5cIRkJ

#### Todo

There does not appear to be a similar concept to service message in Jenkins. There are however several Jenkins plugins that add similar functionality to Jenkins, e.g. environment script plugin mentioned in the comments thread. We require use of this (or similar) plugin:

 * [x] select a plugin - Going for [EnvInject]
  * [x] Evaluate [EnvironmentScript]. Cannot be used; can only be run from .sh ish shells, which we cannot assume to be present on our .net build slaves IMO
  * [x] Evaluate [EnvInject], e.g. from sample [here](http://stackoverflow.com/questions/10625259/how-to-set-environment-variables-in-jenkins). This one would work.
 * [ ] implement `/buildserver` with tests for Jenkins CI
 * [x] set up jenkins job that runs agains my fork, building the propertiesfile_output branch. Build steps:
   * [x] 1. create gitversion binary
   * [x] 2. run this binary to generate environment variables pipe to gitversion.properties file
   * [x] 3. in the next step verify (by simply printing) the values of the environment variables set
 * [x] Update documentation
 * [x] Open PR

   

 [EnvInject]: https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin
 [EnvironmentScript]: https://wiki.jenkins-ci.org/display/JENKINS/Environment+Script+Plugin

**Comment by pvandervelde** [comment]
@serra Has there been progress on this? Any chance of getting this into the next release?

**Comment by serra** [comment]
@pvandervelde no progress thusfar; since Jenkins does not have a concept similar to Service Messages, this would mean a fundamentally different implementations than the current TeamCity and similar implementations. 

I guess I could cook up a (IMO) hackish implementation similar to the current `AppVeyor.cs` implementation (which seems to be making http calls in the `GenerateSetVersionMessage` and `GenerateSetParameterMessage ` methods. But that does not sit right with me and I don't consider it an improvement over my current solutions:

 1. simply use gitversion in psake build script (works on all windows build machines)
 1. json to java properties file and then us EnvInject (which I did use, but not anymore)

Best integration with Jenkins would be to be able to do something like:

```
gitversion /output props > envvars.properties
```

Which could then be injected into Jenkins using the EnvInject plugin.

**Comment by pvandervelde** [comment]
That's roughly what I'm doing currently. The main issue is that GitVersion behaves differently if it thinks it's on a build server than when it's on a dev machine. It normalizes branches on the build machine and not on the dev machine (as far as I know). The problem I have with Jenkins is that Jenkins doesn't pull all the history, just the commit and it doesn't even put that commit on a proper branch (uses a detached head instead) which stuffs up GitVersion.

**Comment by JakeGinnivan** [comment]
#507 could help with this. It would also be good to get the current approaches documented. Would either of you be up for submitting a PR with some info on setting up jenkins at https://github.com/GitTools/GitVersion/blob/master/docs/more-info/build-server-setup/jenkins.md ?

**Comment by pvandervelde** [comment]
I can probably have a look at the configuration we use at work when I'm back there next week. Mind you I haven't found a good setup to get the branch names to work out yet.

**Comment by serra** [comment]
@JakeGinnivan would you accept a PR for `/output props` that instead of

```
C:\dev\Gitversion\src>gitversion /output json
{
  "Major":3,
  "Minor":0,
  "Patch":1,
  "PreReleaseTag":"",
  // ...
  "SemVer":"3.0.1",
  // ...
```
writes out 

```
C:\dev\Gitversion\src>gitversion /output props
gitversion.Major=3
gitversion.Minor=0
gitversion.Patch=1
gitversion.PreReleaseTag=
# ...
gitversion.SemVer=3.0.1
# ...
```

That output would be trivial to use with the EnvInject plugin.

**Comment by serra** [comment]
Or do you prefer a Jenkins `Jenkins:BuildServerBase` implementation that produces mentioned output?

I prefer the `/output props` because of it's clarity; the buildserver implies some sort of build server integration, which in fact is not provided, because users have to automate the use of the output themselves.

**Comment by serra** [comment]
Note to self A suitable jenkins implementation might be one that saves the `gitversion /output props` from PR #534 to gitversion.properties to be picked up by EnvInject or other plugin.

**Comment by serra** [comment]
Fixed with merge of PR #551
